### PR TITLE
Hugo

### PR DESCRIPTION
**Pull request by moxiegirl**
Testing one or two things.

### CODE REVIEW

**Comment by SvenDowideit** [comment]
isn't it fun when you get a zero-changes PR :)

**Comment by moxiegirl** [comment]
@SvenDowideit  I was in a state of befuddlement and stumbled into it. :-P

**Comment by thaJeztah** [comment]
LOL thought I had a bit too much to drink or it was a PR to test some webhook/trigger.

changes LGTM, think this is safe to merge :smiley:

**Comment by moxiegirl** [comment]
Thanks Sven.

**Pull request merged**
