### PR TITLE
Removing cloud layouts

### PR DESCRIPTION
**Pull request by moxiegirl**
Fix a problem in the tutum Cloud layout.  

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
@SvenDowideit @thaJeztah take a peak. I'm just removing something I added for Docker Cloud.

**Comment by thaJeztah** [comment]
Ah, so that's how you do it! "-70"


LGTM, I guess :-)

**Comment by moxiegirl** [comment]
-70? Author LGTM.

**Comment by thaJeztah** [comment]
This "-70" :smile:
screen shot 2016-01-26 at 18 57 23

**Pull request merged**
