### PR TITLE
Reduce letter spacing

### PR DESCRIPTION
**Pull request by bfirsh**
Makes everything much neater and easier to read.

Before:

screenshot 2016-04-28 16 15 43

After:

screenshot 2016-04-28 16 15 36

This brings it in line with docker.com's styles. There are still a bunch of differences between docker.com and docs.docker.com, but they have diverged so much that vendoring docker.com into docs.docker.com properly would be a much larger piece of work.

As part of this, I have also put the system for compiling the theme static assets inside a Docker container.

### CODE REVIEW

**Comment by estesp** [comment]
Wow, I'm no docs maintainer, but I really like the readability improvement in the screenshot--I never could place my finger on it, but docs.docker.com always looked different than many other sites. I think this reduction in letter spacing is visibly much more appealing.

**Comment by SvenDowideit** [comment]
TOTALLY +1 for containerizing the them build, I was just about to poke that.

I've asked the rest of the docs team to opin

I'm also going to look into seeing how out of date our copy of the marketing site is - i know nothing about this theme.

from my POV 

# LGTM

**Comment by thaJeztah** [comment]
+1 from me as well (typography could use a bit of TLC in our docs)

LGTM

**Comment by sfsmithcha** [comment]
@SvenDowideit wondering how to test this. Built from this PR locally and see the narrower letter spacing, but I'm still seeing the boxes around inline code in the archived docs. Not seeing any relevant topics in the main docs space.

**Comment by SvenDowideit** [comment]
@sfsmithcha this PR doesn't change the orange borders, but I'll use the build changes here to re-do that one :)

**Pull request merged**
