### PR TITLE
make the example test menu draft, so it won't show in builds

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@sanscontext @londoncalling @sfsmithcha @joaofnfernandes

**Comment by sfsmithcha** [comment]
LGTM

**Comment by sanscontext** [comment]
LGTM

**Comment by londoncalling** [comment]
LGTM

**Pull request merged**
