### PR TITLE
Updating new menu

### PR DESCRIPTION
**Pull request by moxiegirl**
Removing the product navigation from docs-base.  Each product will handle its own navigation.  We are moving to product-specific navigation for 1.10.

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
@thaJeztah @SvenDowideit please review gents.

**Comment by thaJeztah** [comment]
LGTM

slightly related, but should we have a separate build-target for testing the docs base (e.g. using a separate Dockerfile)?

**Comment by moxiegirl** [comment]
@thaJeztah idk, seems like we test it every time we do a local build...:-D  If you want to open a PR, feel free.

**Comment by thaJeztah** [comment]
alright, let's merge!

**Pull request merged**
