### PR TITLE
Put the things in the license

### PR DESCRIPTION
**Pull request by bfirsh**
lionel-hutz

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks @bfirsh, this change LGTM

@moxiegirl does this repo also need a dual license (i.e. "creative commons" for docs); ref https://github.com/docker/libkv/pull/59

**Comment by moxiegirl** [comment]
@thaJeztah Yes it does.  I'll add them in today.

**Comment by thaJeztah** [comment]
@moxiegirl should we merge this in the meantime ?

**Comment by moxiegirl** [comment]
Yess..LGTM

**Pull request merged**
