### PR TITLE
Adding in the mobile

### PR DESCRIPTION
**Pull request by moxiegirl**
Moving over https://github.com/docker/docker/pull/9726

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
@SvenDowideit We had a user will-ob do some cool mobile css

**Comment by SvenDowideit** [comment]
setting up to test today

**Comment by SvenDowideit** [comment]
@will-ob, what devices did you test with? browserstack doesn't show even one example where the change works as desired :(

**Comment by SvenDowideit** [comment]
Ah. wonderful. it works in interactive mode, but not static screenshot mode.

looking good for mobiles - much harder for high res tablets in portrait mode.

**Comment by will-ob** [comment]
:+1: shweet -- thanks for working this in, All

fwiw, I've been using [dimensions toolkit](http://www.dimensionstoolkit.com/). It's worked pretty great

**Comment by moxiegirl** [comment]
thanks @SvenDowideit !

**Pull request merged**
