### PR TITLE
Remove unused pages and images

### PR DESCRIPTION
**Pull request by dnephin**
While looking around for the solution to #153 I discovered we have 3 copies of this `docker-friends.png` image. I couldn't find these used anywhere so I'm submitting this PR to remove them.  Let me know if any of them are needed.

### CODE REVIEW

**Comment by moxiegirl** [comment]
@dnephin These are actually used when I test just this repo.  I run Hugo with the draft removed. So they are useful for doing things like checking the menu structs.

**Comment by dnephin** [comment]
OK, good to know. I'll restore the test markdown files. I believe the images copies can be removed still, right?

**Comment by dnephin** [comment]
Restored test markdown files.

**Comment by moxiegirl** [comment]
@dnephin one of the images is used on the front page...The other is a dupe. I'll have to check which it is. I"ll do that shortly.

**Comment by dnephin** [comment]
@moxiegirl The one that is used is at `./static/images/docker-friends.png` , I haven't removed that one.

**Comment by moxiegirl** [comment]
Cool. Ty. Works for me LGTM

**Pull request merged**
