### PR TITLE
Correct URL in release notes

### PR DESCRIPTION
**Pull request by guessi**
compose, swarm put their CHANGELOG.md in release branch

Signed-off-by: guessi <guessi@gmail.com>

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@thaJeztah @moxiegirl ?

**Comment by guessi** [comment]
@SvenDowideit

it's just a friendly notice to clarify the document source,
not really a problem, it would be fine to close it :)

the story,
at the moment I created PR, the date of Docker v1.11.0 release,
some CHANGELOG on master branch was having outdated doc,
but they're all looks good now on master.

**Comment by moxiegirl** [comment]
@guessi the master should always contain the latest.  So the master might be ahead of the release --- if they are updating as they dev.  @thaJeztah is that your understanding?

**Comment by thaJeztah** [comment]
I know that for Docker, we update the release notes in the release branch, but after that merge those changes back to master. I assume Swarm and Compose also merge back to master, but I should check with those teams

**Comment by dnephin** [comment]
You are correct about Compose. That is the workflow we follow as well.

**Comment by guessi** [comment]
@moxiegirl @thaJaztah @dnephin

thanks for clarification, I'll close it now.

**Comment by moxiegirl** [comment]
@guessi Thanks for the PR in any case. The attention to detail and reminding us, the user is watching. ⭐

**Pull request closed without merging**
