### PR TITLE
make docs content full size if the TOC is empty

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

this has always irritated me - and helps quite a bit on the apidocs pages.

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@moxiegirl

**Comment by moxiegirl** [comment]
@SvenDowideit Good idea but did you test this?  Every page includes at least the H1, so for example Kitematic install:

http://docs.docker.com/kitematic/

Would be a candidate for your feature but it does appear to work:

image

**Comment by SvenDowideit** [comment]
oooo, that makes it much harder.

this version works on the swagger page (which is what i tested it on). I'm not 100% sure if i can trick it for the "single h1"

**Comment by moxiegirl** [comment]
Well if you are testing against the `len` value  you should be able to test for an array with a value only populated at the `0` position right?

**Comment by SvenDowideit** [comment]
I'm checking the len of a string containing rendered HTML: `.TableOfContents The rendered table of contents for this content.` poking around to see what other options there are :)

**Comment by moxiegirl** [comment]
Well, if you can get to the string, you can check for a single `<li>` if there is one, don't display.

image

**Comment by SvenDowideit** [comment]
giggle - i thought so too

**Pull request closed without merging**
