### PR TITLE
add new blackfriday sourceRelativeLinksProjectFolder setting for v1.9

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

### CODE REVIEW

**Comment by moxiegirl** [comment]
Since your PR on Hugo hasn't been merged, I can't test this. I'm not willing to merge something that I can't test.

**Comment by SvenDowideit** [comment]
it won't "just start working when a PR downstream merges" - for the docs to use it, we will need another PR to update what version of hugo the Dockerfile imports.

These PR's are to make sure we don't get into the situation we're in with the v1.8 and v1.9 branches, which still contain the `gitHubLinkEval` setting that was changed, and so are broken.

**Comment by moxiegirl** [comment]
I'm not merging what I can't test. Basic principle. When you have the update of Hugo that works with this, feel free to submit a new PR with both changes.

**Comment by SvenDowideit** [comment]
This needs to be combined with a PR in docker/docs.docker.com as this pre-dates my change to use `docs/base` in its `FROM` line.

**Comment by SvenDowideit** [comment]
oh. and this version still uses compose, what "fun"

**Pull request closed without merging**
