### PR TITLE
Adding 1.10 archive to the list

### PR DESCRIPTION
**Pull request by moxiegirl**
Adding 1.10 to the archive list.  
Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
@londoncalling @sanscontext Please review

**Comment by londoncalling** [comment]
LGTM @moxiegirl

**Comment by sanscontext** [comment]
LGTM

**Comment by moxiegirl** [comment]
Thanks!

**Pull request merged**
