### PR TITLE
add new blackfriday sourceRelativeLinksProjectFolder setting for v1.10

### PR DESCRIPTION
**Pull request by SvenDowideit**
preparing for spf13/hugo#1977

can be merged anytime

Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

### CODE REVIEW

**Comment by moxiegirl** [comment]
Since your PR on Hugo hasn't been merged, I can't test this. I'm not willing to merge something that I can't test.

**Comment by SvenDowideit** [comment]
it won't "just start working when a PR downstream merges" - for the docs to use it, we will need another PR to update what version of hugo the Dockerfile imports.

These PR's are to make sure we don't get into the situation we're in with the v1.8 and v1.9 branches, which still contain the `gitHubLinkEval` setting that was changed, and so are broken.

**Comment by moxiegirl** [comment]
I'm not merging what I can't test. Basic principle. When you have the update of Hugo that works with this, feel free to submit a new PR with both changes.

**Comment by SvenDowideit** [comment]
to test, make a modification to docs.docker.com v1.10 branch like

```
root@docker:~/docs.docker.com# git branch
  master
* v1.10
  v1.9
root@docker:~/docs.docker.com# git diff
diff --git a/Dockerfile b/Dockerfile
index 5e066be..f95ad86 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,5 @@
-FROM docs/base:latest
+#FROM docs/base:latest
+FROM docs-base:sourceRelativeLinksProjectFolder-v1.10
 MAINTAINER Mary Anthony <mary@docker.com> (@moxiegirl)

 WORKDIR /src
diff --git a/Makefile b/Makefile
index 0af9953..eb3f3b3 100644
--- a/Makefile
+++ b/Makefile
@@ -34,7 +34,7 @@ all: clean serve

 # The result of this step should become a hub image that the Docker projects can use for local testing
 build:
-       docker pull $(shell grep FROM Dockerfile | sed s/FROM//) || true
+       #docker pull $(shell grep FROM Dockerfile | sed s/FROM//) || true
        docker build \
                -t $(DOCKER_IMAGE) \
```

**Pull request closed without merging**
