### PR TITLE
Add ssed into the base system

### PR DESCRIPTION
**Pull request by moxiegirl**
- supser-sed allows me to use Perl regex and thererfore lookahead in the build scripts

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
@thaJeztah @SvenDowideit

**Comment by thaJeztah** [comment]
lol, never used it, but if it makes it easier to handle things, LGTM :smile:

**Comment by SvenDowideit** [comment]
super! - I like Perl :) 


LGTM

**Comment by moxiegirl** [comment]
Thank you gents!

**Pull request merged**
