### PR TITLE
Made progress

### PR DESCRIPTION
**Pull request by rexington**
We're some of the way there -- definitely not all the way there.

### CODE REVIEW

**Comment by moxiegirl** [comment]
Please rebase and squash your changes, thanks!

**Comment by moxiegirl** [comment]
Never mind. I'll rebase on merge.

**Comment by rexington** [comment]
OK, squashing all of those is going to require a force push, is it not?

**Comment by moxiegirl** [comment]
@rexington  No worries. I'll do it on my end. It might be you don't do rebases very often and they can go squirrley if you are a newb to them.

**Comment by moxiegirl** [comment]
@rexington I just sent you an email.  Can you confirm what I am seeing is the expected result? Cause if it is I don't want to pull your changes right now ... I'd prefer to wait until you have something that looks more reasonable.

**Comment by moxiegirl** [comment]
@rexington kk. I see it now. Please:

- attach the menu as a fixed looking sidebar
- the left hand margin is far too wide

**Comment by rexington** [comment]
Hi Mary, this PR stands -- it has commits added to it.

**Comment by moxiegirl** [comment]
I merged this manually into my branch.   I'm going to close this.

**Comment by rexington** [comment]
added changes

**Comment by moxiegirl** [comment]
Rex,

Thanks for trying to solve the menu issue. Given your time crunch and the uncertainty of receiving a fix we could use, we created a solution in house.

Also, in the run up to the release yesterday, we made changed the design. Betty, I'm sure, has also been discussing changes to header/footer material. So, I'm going to close this -- the first part of your changes are in the last commit is not.  We will need to start from a new branch when work resumes after Dockercon.

Thanks,

Mary

**Pull request closed without merging**
