### PR TITLE
Make Hugo output a warning when there are missing index.md files

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

related to https://github.com/spf13/hugo/issues/1659

Hugo isn't obvious - the error you'll see if complaining that it can't find the layout file:

```
docker run --rm -it  -e AWS_S3_BUCKET -e NOCACHE --name docker-docs-tools -p 8000:8000 -e DOCKERHOST "docs-base:master" hugo server --port=8000 --baseUrl=localhost --bind=0.0.0.0 --config=./config.toml
INFO: 2015/12/02 Using config file: ./config.toml
INFO: 2015/12/02 syncing from /docs/themes/hugo-foundation/static to /docs/public/
INFO: 2015/12/02 syncing from /docs/static/ to /docs/public/
ERROR: 2015/12/02 loadData at 
ERROR: 2015/12/02 LinkResolver: No page found for "/compose/install.md" on page "security/trust/deploying_notary.md".
INFO: 2015/12/02 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
WARN: 2015/12/02 Unable to locate layout for section userguide: [section/userguide.html _default/section.html _default/list.html indexes/userguide.html _default/indexes.html theme/section/userguide.html theme/_default/section.html theme/_default/list.html theme/indexes/userguide.html theme/_default/indexes.html theme/section/userguide.html theme/_default/section.html theme/_default/list.html theme/indexes/userguide.html theme/_default/indexes.html theme/theme/section/userguide.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/userguide.html theme/theme/_default/indexes.html]
WARN: 2015/12/02 Unable to locate layout for section installation: [section/installation.html _default/section.html _default/list.html indexes/installation.html _default/indexes.html theme/section/installation.html theme/_default/section.html theme/_default/list.html theme/indexes/installation.html theme/_default/indexes.html theme/section/installation.html theme/_default/section.html theme/_default/list.html theme/indexes/installation.html theme/_default/indexes.html theme/theme/section/installation.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/installation.html theme/theme/_default/indexes.html]
WARN: 2015/12/02 Unable to locate layout for section articles: [section/articles.html _default/section.html _default/list.html indexes/articles.html _default/indexes.html theme/section/articles.html theme/_default/section.html theme/_default/list.html theme/indexes/articles.html theme/_default/indexes.html theme/section/articles.html theme/_default/section.html theme/_default/list.html theme/indexes/articles.html theme/_default/indexes.html theme/theme/section/articles.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/articles.html theme/theme/_default/indexes.html]
WARN: 2015/12/02 Unable to locate layout for section : [section/.html _default/section.html _default/list.html indexes/.html _default/indexes.html theme/section/.html theme/_default/section.html theme/_default/list.html theme/indexes/.html theme/_default/indexes.html theme/section/.html theme/_default/section.html theme/_default/list.html theme/indexes/.html theme/_default/indexes.html theme/theme/section/.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/.html theme/theme/_default/indexes.html]
WARN: 2015/12/02 Unable to locate layout for section extend: [section/extend.html _default/section.html _default/list.html indexes/extend.html _default/indexes.html theme/section/extend.html theme/_default/section.html theme/_default/list.html theme/indexes/extend.html theme/_default/indexes.html theme/section/extend.html theme/_default/section.html theme/_default/list.html theme/indexes/extend.html theme/_default/indexes.html theme/theme/section/extend.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/extend.html theme/theme/_default/indexes.html]
WARN: 2015/12/02 Unable to locate layout for section introduction: [section/introduction.html _default/section.html _default/list.html indexes/introduction.html _default/indexes.html theme/section/introduction.html theme/_default/section.html theme/_default/list.html theme/indexes/introduction.html theme/_default/indexes.html theme/section/introduction.html theme/_default/section.html theme/_default/list.html theme/indexes/introduction.html theme/_default/indexes.html theme/theme/section/introduction.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/introduction.html theme/theme/_default/indexes.html]
WARN: 2015/12/02 Unable to locate layout for section misc: [section/misc.html _default/section.html _default/list.html indexes/misc.html _default/indexes.html theme/section/misc.html theme/_default/section.html theme/_default/list.html theme/indexes/misc.html theme/_default/indexes.html theme/section/misc.html theme/_default/section.html theme/_default/list.html theme/indexes/misc.html theme/_default/indexes.html theme/theme/section/misc.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/misc.html theme/theme/_default/indexes.html]
WARN: 2015/12/02 Unable to locate layout for section reference: [section/reference.html _default/section.html _default/list.html indexes/reference.html _default/indexes.html theme/section/reference.html theme/_default/section.html theme/_default/list.html theme/indexes/reference.html theme/_default/indexes.html theme/section/reference.html theme/_default/section.html theme/_default/list.html theme/indexes/reference.html theme/_default/indexes.html theme/theme/section/reference.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/reference.html theme/theme/_default/indexes.html]
WARN: 2015/12/02 Unable to locate layout for section examples: [section/examples.html _default/section.html _default/list.html indexes/examples.html _default/indexes.html theme/section/examples.html theme/_default/section.html theme/_default/list.html theme/indexes/examples.html theme/_default/indexes.html theme/section/examples.html theme/_default/section.html theme/_default/list.html theme/indexes/examples.html theme/_default/indexes.html theme/theme/section/examples.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/examples.html theme/theme/_default/indexes.html]
WARN: 2015/12/02 Unable to locate layout for section security: [section/security.html _default/section.html _default/list.html indexes/security.html _default/indexes.html theme/section/security.html theme/_default/section.html theme/_default/list.html theme/indexes/security.html theme/_default/indexes.html theme/section/security.html theme/_default/section.html theme/_default/list.html theme/indexes/security.html theme/_default/indexes.html theme/theme/section/security.html theme/theme/_default/section.html theme/theme/_default/list.html theme/theme/indexes/security.html theme/theme/_default/indexes.html]
0 of 17 drafts rendered
0 future content
169 pages created
117 non-page files copied
0 paginator pages created
0 tags created
0 categories created
in 501 ms
Serving pages from /docs/public
Web Server is available at http://localhost:8000/ (bind address 0.0.0.0)
Press Ctrl+C to stop
```

### CODE REVIEW

**Comment by SvenDowideit** [comment]
@moxiegirl @dnephin @thaJeztah

**Comment by dnephin** [comment]
LGTM as a short-term solution to get more information about these empty pages.

If it doesn't get fixed in hugo, I guess we can do something with the docs validation to find these empty pages?

**Comment by thaJeztah** [comment]
same as @dnephin dirty, but yeah, should be good as a temporary solution

LGTM

**Comment by SvenDowideit** [comment]
yes, I've been adding detection to the linkchecker :)

**Pull request merged**
