### PR TITLE
increased the vibrancy of the iconography on the homepage

### PR DESCRIPTION
**Pull request by FSHA**
Signed-off-by: fish <fisher@docker.com>

@sanscontext updated the icons!! only on the homepage.

Updated the assets and removed the opacity set to them in temporary.

### CODE REVIEW

**Comment by sanscontext** [comment]
LGTM! @SvenDowideit look we found some misbehaving css.

**Comment by sanscontext** [comment]
@fisher checked and it looks like the CSS he removed is only ever used on this page.

**Comment by SvenDowideit** [comment]
LGTM - get it out there! :)

**Comment by fisher** [comment]
Hey, I didn't touch it, I swear!

**Comment by thaJeztah** [comment]
Should we remove the old icons?

**Comment by sanscontext** [comment]
@thaJeztah I have a PR forthcoming to remove some cruft, including my original landing page icons. :)

**Comment by sanscontext** [comment]
Also, sorry for the random tag @fisher - You share a name with @FSHA!

**Pull request merged**
